#!/bin/bash

# Set Region
export AWS_DEFAULT_REGION=ap-northeast-1

# Set Opption
OUTPUT="table"
QUERY="sort_by(Reservations[].Instances[].\
                {InstanceId:InstanceId,\
                 Name:Tags[?Key==\`Name\`].Value|[0],\
                 Ip:PrivateIpAddress,\
                 State:State.Name},&Name)"


# Set Command
EC2_DESCRIBE=`aws ec2 describe-instances --output "$OUTPUT" --query "$QUERY"`


# Main Function
if [ "$1" = "" ]; then

    echo "${EC2_DESCRIBE}" | grep -Ei "(Instance|\-{2}|)"

else

    echo "${EC2_DESCRIBE}" | grep -Ei "(Instance|\-{2}|$1)"

fi

